# A könyv alapadatai
[book]
authors = ["Freud Andrea"]
language = "hu"
multilingual = false
src = "src"
title = "Útmutató kezdőtől haladó szintig a programozáshoz"

# Megjelenés és HTML beállítások
[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
search = true

# Fontos: A link végére kell a /{path}, hogy az adott oldal szerkesztésére vigyen!
git-repository-url = "https://github.com/Nagraggini/my-awesome-book"
edit-url-template = "https://github.com/Nagraggini/my-awesome-book/edit/main/src/{path}"

# Kódblokk beállítások (Playpen)
[output.html.playground]
enabled = true
editable = true
copyable = true
line-numbers = true

# Figyelemfelhívó dobozok (admonitions)
[preprocessor.admonition]