name: deploy
on:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install mdBook
              run: |
                  # Itt az idézőjel a lényeg!
                  curl -sSL "https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz" | tar -xz
                  chmod +x mdbook
                  sudo mv mdbook /usr/local/bin/

            - name: Build and Deploy
              run: mdbook build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4 # Erre a gp-pages-re kell átállítani a Settings -> Pages-ben.
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./book
